#!/bin/sh
export EDITOR=/home/h4rr9/builds/neovim/bin/nvim
export VISUAL=topen
export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8 

HISTSIZE=1000000
SAVEHIST=1000000

export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export PATH=$HOME/builds/neovim/bin:$PATH
export PATH=$HOME/builds/tmux/bin:$PATH
export PATH=/usr/local/go/bin:$HOME/go/bin:$PATH
export PATH=$PATH:./node_modules/.bin
export PATH=/usr/local/texlive/2021/bin/x86_64-linux:$PATH

export MANPAGER='nvim +Man!'
export MANWIDTH=999

export GOPATH=$HOME/.local/share/go
export BAT_THEME="gruvbox-dark"
export _ZO_DATA_DIR=$HOME/.local/share

export GPG_AGENT_INFO=$HOME/.gnupg/S.gpg-agent:0:1
export GPG_TTY=$TTY

eval "$(zoxide init zsh)"


if [[ ! -a ~/.gnupg/S.gpg-agent ]]; then
    eval  $(gpg-agent --daemon --options ~/.gnupg/gpg-agent.conf) > /dev/null

fi


